<a href="https://colab.research.google.com/github/fraserrbarclay/Python-Data-Practicals/blob/main/project/masculinity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring data sets
---

This [link](https://docs.google.com/document/d/1cijDOCDixsYu-Rr9pC8STPPXado3xoFpgBAZgdDTLHs/edit?usp=sharing) will take you to a list of some of the datasets we use during the Programming for Data course.

For this exercise, please choose a dataset to work with.

Use the code cell below to play with the data.  Look at what data is included, where there is any null data, if there are any columns that need renaming, removing, new values calculated from them.

Form some ideas of what you might want to know from the data and use the techniques you have learned so far to show the answers to these.  You might do this by getting summary statistics, by sorting and showing parts of the dataset, by calculating new values, etc.

### What to do
---

Decide what you want to know, explain this in the TEXT cell below, then write some code to get the answer.  When you have done this, add a new text cell below the code cell, explain what you have found.  Then do the same again, adding text cell, code cell, text cell, for something else you would like to know.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://github.com/fraserrbarclay/Python-Data-Practicals/raw/main/data/raw-responses.csv')

In [ ]:
survey = pd.read_csv('https://github.com/fraserrbarclay/Python-Data-Practicals/raw/main/data/masculinity-survey.csv')

In [ ]:
qs = survey['AMONG ADULT MEN'].dropna().reset_index()['AMONG ADULT MEN']

In [ ]:
for column in ['Unnamed: 0','StartDate','EndDate']:
  del df[column]

In [ ]:
import numpy as np
for i in range (0 , len(df.columns)):
  df.loc[df.iloc[:, i] == 'Not selected', df.columns[i]] = np.nan
  df.loc[df.iloc[:, i] == 'No answer', df.columns[i]] = np.nan

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 46 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   q0001        1601 non-null   object
 1   q0002        1606 non-null   object
 2   q0004        1601 non-null   object
 3   q0005        1602 non-null   object
 4   q0007_0001   1599 non-null   object
 5   q0007_0002   1596 non-null   object
 6   q0007_0003   1601 non-null   object
 7   q0007_0004   1524 non-null   object
 8   q0007_0005   1606 non-null   object
 9   q0007_0006   1580 non-null   object
 10  q0007_0007   1594 non-null   object
 11  q0007_0008   1601 non-null   object
 12  q0007_0009   1574 non-null   object
 13  q0007_0010   1580 non-null   object
 14  q0007_0011   1587 non-null   object
 15  q0008        1612 non-null   object
 16  q0009        1612 non-null   object
 17  q0010        877 non-null    object
 18  q0011        875 non-null    object
 19  q0012        873 non-null    object
 20  q0013        48 non-null     object
 21  q0014        879 non-null    object
 22  q0015        736 non-null    object
 23  q0017        1584 non-null   object
 24  q0018        1574 non-null   object
 25  q0019        1247 non-null   object
 26  q0020        1574 non-null   object
 27  q0021        1581 non-null   object
 28  q0022        1586 non-null   object
 29  q0024        1607 non-null   object
 30  q0025        1606 non-null   object
 31  q0026        1602 non-null   object
 32  q0028        1615 non-null   object
 33  q0029        1615 non-null   object
 34  q0030        1615 non-null   object
 35  q0034        1613 non-null   object
 36  q0035        1595 non-null   object
 37  q0036        1613 non-null   object
 38  race2        1615 non-null   object
 39  racethn4     1615 non-null   object
 40  educ3        1615 non-null   object
 41  educ4        1615 non-null   object
 42  age3         1615 non-null   object
 43  kids         1606 non-null   object
 44  orientation  1602 non-null   object
 45  weight       1615 non-null   float64
dtypes: float64(1), object(45)
memory usage: 580.5+ KB

In [ ]:
def collapse_columns(df, first, last, name):
  q = df.iloc[:,first:last] .stack().reset_index(drop=False)
  q = q[['level_0',0]]
  q = q.groupby('level_0')[0].apply(list)

  deleted = df.iloc[:,first:last].columns
  for i in deleted:
    del df [i]

  df.insert(first,name ,q)
  return df

df = collapse_columns(df, 2,8 , 'q0004')

In [ ]:
df = collapse_columns(df , 15, 27 , 'q0008')

In [ ]:
df = collapse_columns(df,17,25,'q0010')

In [ ]:
df = collapse_columns(df,18,23,'q0011')

In [ ]:
df = collapse_columns(df,19,26,'q0012')

In [ ]:
df = collapse_columns(df,25,32,'q0019')

In [ ]:
df = collapse_columns(df,26,32,'q0020')

In [ ]:
df = collapse_columns(df,27,31,'q0021')

In [ ]:
df = collapse_columns(df,30,33,'q0025')

In [ ]:
df

,q0001,q0002,q0004,q0005,q0007_0001,q0007_0002,q0007_0003,q0007_0004,q0007_0005,q0007_0006,...,q0035,q0036,race2,racethn4,educ3,educ4,age3,kids,orientation,weight
0,Somewhat masculine,Somewhat important,[Pop culture],Yes,Often,Often,Often,Often,"Never, and not open to it","Never, and not open to it",...,Middle Atlantic,Windows Desktop / Laptop,Non-white,Hispanic,College or more,College or more,35 - 64,No children,Gay/Bisexual,1.714026
1,Somewhat masculine,Somewhat important,[Father or father figure(s)],Yes,Rarely,Sometimes,"Never, but open to it",Rarely,"Never, and not open to it",Rarely,...,East North Central,iOS Phone / Tablet,White,White,Some college,Some college,65 and up,Has children,Straight,1.247120
2,Very masculine,Not too important,"[Father or father figure(s), Other (please spe...",No,Sometimes,Sometimes,Sometimes,Rarely,"Never, but open to it",Often,...,East North Central,Windows Desktop / Laptop,White,White,College or more,College or more,35 - 64,Has children,Straight,0.515746
3,Very masculine,Not too important,"[Father or father figure(s), Mother or mother ...",No,Rarely,Rarely,Sometimes,Rarely,Rarely,Often,...,East North Central,Windows Desktop / Laptop,White,White,Some college,Some college,65 and up,Has children,NaN,0.600640
4,Very masculine,Very important,[Other family members],Yes,Sometimes,Rarely,"Never, and not open to it","Never, but open to it","Never, but open to it",Sometimes,...,East North Central,Windows Desktop / Laptop,White,White,College or more,College or more,35 - 64,No children,Straight,1.033400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610,Not very masculine,Not at all important,"[Father or father figure(s), Mother or mother ...",Yes,Rarely,Sometimes,"Never, and not open to it",Rarely,"Never, and not open to it","Never, but open to it",...,West North Central,iOS Phone / Tablet,White,White,Some college,Some college,18 - 34,No children,Straight,2.891038
1611,Very masculine,Very important,"[Father or father figure(s), Other family memb...",Yes,Often,Often,Sometimes,"Never, but open to it",Rarely,Often,...,NaN,iOS Phone / Tablet,Non-white,Hispanic,High school or less,High school or less,35 - 64,Has children,Straight,8.643674
1612,Somewhat masculine,Somewhat important,[Mother or mother figure(s)],Yes,NaN,Often,Often,Rarely,Rarely,Often,...,South Atlantic,Windows Desktop / Laptop,White,White,Some college,Some college,35 - 64,Has children,Straight,2.340241
1613,Somewhat masculine,Somewhat important,[Mother or mother figure(s)],Yes,Sometimes,Sometimes,"Never, but open to it","Never, but open to it","Never, but open to it",Often,...,Mountain,Windows Desktop / Laptop,White,White,High school or less,High school or less,18 - 34,No children,Straight,6.557984
1614,Very masculine,Not at all important,"[Father or father figure(s), Mother or mother ...",No,Often,Sometimes,Rarely,Rarely,Sometimes,Often,...,Middle Atlantic,iOS Phone / Tablet,White,White,Some college,Some college,18 - 34,No children,Straight,2.817560